using commerceApi.Data.Repositories;
using commerceApi.Models;
using MediatR;

namespace commerceApi.Features.Customers.Commands;

// =============================================================================
// LEARNING NOTE: Why the Command Only Contains the Data Needed to CREATE
// =============================================================================
//
// Notice that CreateCustomerCommand has: FirstName, LastName, Email
// It does NOT have: Id or CreatedAt
//
// WHY?
//   - Id is auto-generated by PostgreSQL (SERIAL / GENERATED ALWAYS AS IDENTITY)
//     The client doesn't choose the ID — the database assigns it.
//
//   - CreatedAt is set by the database using DEFAULT NOW() or CURRENT_TIMESTAMP.
//     The server clock is the source of truth, not the client's clock.
//
// If we let the client send an Id, bad things could happen:
//   - They could overwrite an existing customer (accidental or malicious)
//   - Two clients could choose the same ID (collision)
//   - IDs wouldn't be sequential (harder to debug and query)
//
// If we let the client send CreatedAt:
//   - They could backdate records (data integrity issue)
//   - Time zone confusion between client and server
//   - Inconsistent timestamps across records
//
// THE PATTERN:
//   Command record  → only fields the CLIENT controls
//   Database         → generates Id, CreatedAt, UpdatedAt, etc.
//   Response         → returns the FULL entity (with generated fields)
//
// This is why CreateAsync returns a Customer (not void) — the controller needs
// the complete object (with Id and CreatedAt) to return in the 201 response.
// =============================================================================

/// <summary>
/// Command to create a new customer. Only includes fields the client provides.
/// The database generates Id and CreatedAt automatically.
/// </summary>
public sealed record CreateCustomerCommand(
    string FirstName,
    string LastName,
    string Email
) : IRequest<Customer>;

/// <summary>
/// Handler that creates a new customer via the repository.
/// Returns the full Customer object including database-generated fields.
/// </summary>
public sealed class CreateCustomerHandler : IRequestHandler<CreateCustomerCommand, Customer>
{
    private readonly ICustomerRepository _customerRepository;

    public CreateCustomerHandler(ICustomerRepository customerRepository)
    {
        _customerRepository = customerRepository;
    }

    public async Task<Customer> Handle(CreateCustomerCommand request, CancellationToken cancellationToken)
    {
        // Map the command to a Customer model.
        // Id is 0 (default) and CreatedAt is default — both will be set by the database.
        var customer = new Customer
        {
            FirstName = request.FirstName,
            LastName = request.LastName,
            Email = request.Email
        };

        // CreateAsync returns the customer WITH the database-generated Id and CreatedAt.
        return await _customerRepository.CreateAsync(customer);
    }
}
